# Generated by Django 4.1.4 on 2023-01-14 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Others', 'Others'), ('Food and Dining', 'Food and Dining'), ('Shopping', 'Shopping'), ('Travelling', 'Travelling'), ('Entertainment', 'Entertainment'), ('Medical', 'Medical'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Bills and Utilities', 'Bills and Utilities'), ('Rent', 'Rent'), ('Taxes', 'Taxes'), ('Insurance', 'Insurance'), ('Gifts and Donation', 'Gifts and Donation')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('note', models.TextField()),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
