# Generated by Django 4.1.4 on 2023-04-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Others', 'Others'), ('Food and Dining', 'Food and Dining'), ('Shopping', 'Shopping'), ('Travelling', 'Travelling'), ('Entertainment', 'Entertainment'), ('Medical', 'Medical'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Bills and Utilities', 'Bills and Utilities'), ('Rent', 'Rent'), ('Taxes', 'Taxes'), ('Insurance', 'Insurance'), ('Gifts and Donation', 'Gifts and Donation')], max_length=500),
        ),
    ]
